# questions.py
# v1 question pool — system-level probes

QUESTIONS = [
    {
        "id": "Q1",
        "domain": "load_capacity",
        "construct": "load_vs_capacity",
        "grammar": "outcome_first",
        "skin": "general",
        "prompt": "When demands increase faster than available capacity, what happens first?",
        "options": [
            "Effort is redistributed internally",
            "Non-essential activity is deferred",
            "Output quality becomes uneven",
            "Short-term throughput is prioritized",
            "Coordination becomes harder",
        ],
    },
    {
        "id": "Q2",
        "domain": "feedback",
        "construct": "feedback_latency",
        "grammar": "process_first",
        "skin": "general",
        "prompt": "When results are slow to appear, how does the system proceed?",
        "options": [
            "It continues based on prior assumptions",
            "It pauses to reassess direction",
            "It seeks informal signals",
            "It increases activity to compensate",
            "It narrows focus to fewer actions",
        ],
    },
    {
        "id": "Q3",
        "domain": "coherence",
        "construct": "effort_to_progress",
        "grammar": "emergence",
        "skin": "general",
        "prompt": "When effort does not reliably translate into progress, what emerges?",
        "options": [
            "Process refinement",
            "Frustration without action",
            "Experimentation",
            "Reduced engagement",
            "Overextension",
        ],
    },
    {
        "id": "Q4",
        "domain": "control",
        "construct": "constraint_clarity",
        "grammar": "signal_shift",
        "skin": "general",
        "prompt": "When constraints are unclear, what tends to change first?",
        "options": [
            "Decision speed",
            "Confidence in choices",
            "Internal coordination",
            "Willingness to commit",
            "Attention distribution",
        ],
    },
    {
        "id": "Q5",
        "domain": "persistence",
        "construct": "sustained_strain",
        "grammar": "time_course",
        "skin": "general",
        "prompt": "When strain persists without a clear endpoint, what shifts first?",
        "options": [
            "Energy allocation",
            "Error tolerance",
            "Planning horizon",
            "Communication clarity",
            "Internal alignment",
        ],
    },
    {
        "id": "Q6",
        "domain": "adaptation",
        "construct": "failed_correction",
        "grammar": "response_chain",
        "skin": "general",
        "prompt": "When corrective actions do not produce relief, what follows?",
        "options": [
            "New strategies are tested",
            "Existing methods are intensified",
            "Scope is reduced",
            "Doubt increases",
            "Stability degrades",
        ],
    },
    {
        "id": "Q7",
        "domain": "recovery",
        "construct": "capacity_recovery",
        "grammar": "resource_signal",
        "skin": "general",
        "prompt": "When recovery time shortens repeatedly, what changes?",
        "options": [
            "Throughput",
            "Precision",
            "Risk tolerance",
            "Adaptability",
            "Sustainability",
        ],
    },
    {
        "id": "Q8",
        "domain": "error",
        "construct": "error_accumulation",
        "grammar": "system_state",
        "skin": "general",
        "prompt": "When errors accumulate faster than they can be resolved, what emerges?",
        "options": [
            "Improved detection",
            "Local fixes",
            "Systemic drift",
            "Defensive behavior",
            "Structural instability",
        ],
    },
    {
        "id": "Q9",
        "domain": "direction",
        "construct": "short_long_conflict",
        "grammar": "trajectory",
        "skin": "general",
        "prompt": "When short-term actions do not support long-term direction, what happens?",
        "options": [
            "Direction is clarified",
            "Tension accumulates",
            "Long-term goals are deferred",
            "Short-term wins dominate",
            "Coherence erodes",
        ],
    },
    {
        "id": "Q10",
        "domain": "boundaries",
        "construct": "boundary_enforcement",
        "grammar": "pressure_response",
        "skin": "general",
        "prompt": "When boundaries are tested repeatedly, what happens?",
        "options": [
            "Boundaries strengthen",
            "Exceptions multiply",
            "Enforcement weakens",
            "Friction increases",
            "Structure collapses",
        ],
    },
    {
        "id": "Q11",
        "domain": "ownership",
        "construct": "responsibility_control_gap",
        "grammar": "imbalance",
        "skin": "general",
        "prompt": "When responsibility exceeds control, what emerges?",
        "options": [
            "Innovation",
            "Stress",
            "Detachment",
            "Overreach",
            "Reprioritization",
        ],
    },
    {
        "id": "Q12",
        "domain": "signal",
        "construct": "signal_trust",
        "grammar": "signal_priority",
        "skin": "general",
        "prompt": "When signals are mixed, which are trusted most?",
        "options": [
            "Quantitative data",
            "Qualitative feedback",
            "Intuition",
            "Authority",
            "Momentum",
        ],
    },
]
